name: Deploy to AWS EC2 Instance

on:
  workflow_run:
    workflows: ["docker-image", "terraform"]
    types:
      - completed

jobs:
  deploy-to-aws:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.id == ${{ github.run_id }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CD }}
          aws-region: us-east-1

      - name: Trigger deployment
        run: |
                    aws deploy create-deployment \
                    --application-name Quizz_App \
                    --deployment-group-name Sample_DepGroup \
                    --github-location repository="teee1307/react-js-cd",commitId="${{ github.sha }}"
                    
                    --target-instances "tag:Name=CodeDeployDemo"
                
