name: Deploy to AWS EC2 Instance

on:
  workflow_run:
    workflows: ["docker-image","terraform"]
    types:
      - completed

jobs:
  deploy-to-aws:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.id == ${{ github.run_id }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy the app
        run: |
          aws deploy create-deployment \
          --application-name quizz-app \
          --deployment-group-name quizz-app-dev \
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CD }}
          AWS_DEFAULT_REGION: us-east-1

