name: Build and Upload Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t my-quiz-app .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Docker image
        run: |
          docker tag my-quiz-app ${{ secrets.DOCKERHUB_USERNAME }}/my-quizz-ci-cd:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-quiz-ci-cd:latest
